### ISSUE TITLE
Make header / sidebar sticky

### ISSUE THREAD

**Issue by mcdonnelldean** [Concorda/concorda-dashboard#50]
When the size of the page is greater than the viewport the header and sidebar scroll away. Can we make it so only the inner portion or 'page' scrolls when taller than the viewport?

**Comment by mcdonnelldean** [comment]
I can bring back over to Vidi when done.

**Comment by thefoxis** [comment]
@mcdonnelldean — just to make sure, is that what you mean? I played around with that but haven't made it work just yet; it's a little bit complicated with the current structure and flexbox. Need to spend more time than I had today to make that work. Some markup alterations might be necessary too

![untitled 2](https://cloud.githubusercontent.com/assets/375731/12542923/963b6c08-c37d-11e5-824a-e61ddba1c438.png)

**Comment by mcdonnelldean** [comment]
Yup, this is it, the footer can scroll with the page, otherwise it would just take up space. 

I'm happy to make any modifications we need for this, let me know what needs to be modified.

**Comment by thefoxis** [comment]
The sidebar doesn't push the content away anymore, I believe I removed all the handlers and styles for that behaviour too. It's going to be closed by default, as I think that's a more expected behaviour as well. Need to fix the scroll of the content still.

**Comment by thefoxis** [comment]
I'm pretty confident this works as intended now. On mobile (smartphones, excluding tablets) the footer has a little shadow on top because of the content scrolling behind it. Also maybe it'd be good to actually not make the footer sticky on mobile because it limits the real estate for scrolling and on smaller phones (less height) it's visible and overlapping the log in and other forms. What do you think?

**Comment by mcdonnelldean** [comment]
I wouldn't make the footer sticker at all.

Kindest Regards,

Dean
